### ISSUE TITLE
Fail2ban reload not working on first run

### ISSUE THREAD

**Issue by sylvainar** [debops/ansible-fail2ban#11]
Hey !

I'm deploying fail2ban with Ansible on my Debian 8 VPS, everything works perfectly, but fail2ban installation throws an error, stopping my ansible script : 

    RUNNING HANDLER [debops.fail2ban : Reload fail2ban] ****************************

    fatal: [vps344828.ovh.net]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to reload service fail2ban: Failed to reload fail2ban.service: Job type reload is not applicable for unit fail2ban.service.\n"}

When I launched the script one more time, it works without errors. The issue is that I need to launch twice and I don't know why.

Can you please help me on this ? 

Thanks a lot !

**Comment by drybjed** [comment]
Are you sure that you are using the current version of the role? In the `master` branch there's no "Reload fail2ban" handler. If you use the version from Ansible Galaxy, I suspect that it's time for a release. Can you confirm?

**Comment by sylvainar** [comment]
You're right, the CHANGES.rst is set on v0.1.0

I'll switch on the github version. Are you planning on releasing on Ansible Galaxy?

Thanks for your work!

**Comment by drybjed** [comment]
@sylvainar Done, the new version is now on Ansible Galaxy.

**Comment by sylvainar** [comment]
Great, thanks !
