### ISSUE TITLE
lookup plugin (template_src) not found

### ISSUE THREAD

**Issue by moemen** [debops/ansible-fail2ban#2]
I'm using debops.fail2ban role alone, and it gives me this error:

fatal: [default] => Failed to template {{ lookup("template_src", "etc/fail2ban/fail2ban.local.j2")
 }}: lookup plugin (template_src) not found                                                           

FATAL: all hosts have already failed -- aborting                                                      

I'm using ansible 1.9.1

**Comment by drybjed** [comment]
You need a custom Ansible lookup plugin, available [here](https://github.com/debops/debops-playbooks/blob/master/playbooks/lookup_plugins/template_src.py).

**Comment by moemen** [comment]
:+1:
I got it. Thanks :smile:

**Comment by jlerbsc** [comment]
Hi, How to install it? and why is not it installed automatically?

**Comment by drybjed** [comment]
@jlerbsc The plugins are available [in the debops-playbooks repository](https://github.com/debops/debops-playbooks/tree/master/playbooks/lookup_plugins), they are not included with Ansible. If you use `debops-playbooks` repository, they are provided automatically; if not, you need to care of that manually.

**Comment by jlerbsc** [comment]
Thanks for your response,
I have cloned debops-playbooks repository.Is there a path to setup to use theses python scripts from another playbook? I try to setup PYTHONPATH but i have always error "lookup plugin (template_src) not found".

**Comment by drybjed** [comment]
You usually put them where the `lookup_plugins` configuration parameter in `ansible.cfg` points to.
