### ISSUE TITLE
Can you create a release version with the last changes?

### ISSUE THREAD

**Issue by lpaulmp** [debops/ansible-fail2ban#26]
I'm trying to lock a version to use in long-term but the last changes in master don't have a tag.

**Comment by drybjed** [comment]
Done.

**Comment by lpaulmp** [comment]
wow it was fast, thanks @drybjed

**Comment by lpaulmp** [comment]
@drybjed can you public the new version on https://galaxy.ansible.com/debops/fail2ban/?

**Comment by drybjed** [comment]
I thought that hooks will do it automacially, but i guess not. Done. BTW, just so you're aware, main development is now done in the [DebOps monorepo](https://github.com/debops/debops/), you might consider switching to it if you use more DebOps roles.

**Comment by lpaulmp** [comment]
the hook should be automatically but looks the build failed no sure if this could be the reason for the issue.
