### ISSUE TITLE
Default SSH Jail broken in Ubuntu 20.04

### ISSUE THREAD

**Issue by Keridos** [debops/ansible-fail2ban#27]
The default sshd jail fails on Ubuntu 20.04 with the following log: https://gist.github.com/Keridos/800234d58db78c6715f78a94b9a2a6f9

**Comment by DEvil0000** [comment]
On ubuntu 20.04 there is no iptables-xt_recent-echo-reject action by default but a iptables-xt_recent-echo action.
The default action however is iptables-multiport.

**Comment by Keridos** [comment]
> 
> 
> On ubuntu 20.04 there is no iptables-xt_recent-echo-reject action by default but a iptables-xt_recent-echo action.
> The default action however is iptables-multiport.

https://github.com/debops/debops/pull/1508
