### ISSUE TITLE
Restart fail2ban doesn't throw errors

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-fail2ban#6]
I'm still working on #5, but I've been running into this a lot when testing. Ansible says fail2ban restarted correctly when in fact it has not. You can see there's an error if you run `service fail2ban restart` manually. 

Not sure if there's anything we can do about that. It would be good if the playbook could stop if there's an error in the fail2ban config.

**Comment by drybjed** [comment]
Since the issue was reported a few months ago, any new developments? Can you show the output of

```
debops service/fail2ban
```

Does it happen each time you run the playbook, or only the first time the host is configured?

**Comment by drybjed** [comment]
Also, what Ansible version, what OS release?

**Comment by carlalexander** [comment]
It was with the older fail2ban on trusty. There's a new issue now where it does throw an error. It was mentioned [here](https://github.com/carlalexander/debops-wordpress/issues/89#issuecomment-242383064).

**Comment by carlalexander** [comment]
[This](https://github.com/fail2ban/fail2ban/issues/1518) might be relevant.

**Comment by carlalexander** [comment]
This seems to be ok now. Closing.
